/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef SCUMM_HD_OBJECT_MANAGER_H
#define SCUMM_HD_OBJECT_MANAGER_H

#include "common/str.h"
#include "common/hashmap.h"
#include "common/hash-str.h"
#include "common/list.h"
#include "graphics/surface.h"

namespace Scumm {

class ScummEngine;
class ObjectData;

/**
 * Manages HD replacement textures for game objects in COMI.
 *
 * Uses object_map.json (generated by scripts/build_object_map.py)
 * to map obj_nr → HD PNG filenames.
 *
 * Object PNG naming: {room:04d}_{name}_{state:04d}.png
 * Object layer PNG naming: same format (pre-composited on background)
 */
class HdObjectManager {
public:
	HdObjectManager(ScummEngine *vm);
	~HdObjectManager();

	/** Initialize by loading the mapping file from hd/ directory. */
	bool init(const Common::String &hdPath);

	/** Set an additional fallback path for HD object textures. */
	void setFallbackPath(const Common::String &path) { _fallbackPath = path; }

	/** Load the HD object PNG for a given obj_nr and state.
	 *  Returns true if a matching PNG was loaded into dest. */
	bool loadObject(int obj_nr, int room, int state, Graphics::Surface &dest);

	/** Check if an HD version exists for a given obj_nr/room/state. */
	bool hasObject(int obj_nr, int room, int state) const;

	/** Get the name associated with an obj_nr (from DOBJ mapping). */
	Common::String getObjectName(int obj_nr) const;

	/** Find the first room that has this object in the mapping.
	 *  Returns -1 if the object is not in the map at all.
	 *  Used for inventory items whose files reside in a different
	 *  room (e.g. room 3) than the player's current room. */
	int findObjectRoom(int obj_nr) const;

	/** Returns true if HD object mode is active. */
	bool isEnabled() const { return _enabled; }

private:
	struct ObjectInfo {
		Common::String name;
		Common::HashMap<int, Common::List<int>> roomStates; // room → [states]
	};

	struct TextureCacheEntry {
		Graphics::Surface surface;
		int lastUsed;
	};

	ScummEngine *_vm;
	bool _enabled;

	// Mapping: obj_nr → ObjectInfo
	Common::HashMap<int, ObjectInfo> _objectMap;

	// Reverse: name → obj_nr (for construction from filename)
	Common::HashMap<Common::String, int> _nameToId;

	// Texture cache (key = filename, value = loaded surface + LRU counter)
	Common::HashMap<Common::String, TextureCacheEntry> _textureCache;
	int _lruCounter;

	// Base path for HD assets (e.g. "game/hd")
	Common::String _hdPath;
	Common::String _fallbackPath;

	// Helper: build HD object PNG path from components
	Common::String buildObjectPath(int room, const Common::String &name, int state) const;
	Common::String buildLayerPath(int room, const Common::String &name, int state) const;

	// Load a single PNG into a surface
	bool loadPNG(const Common::String &path, Graphics::Surface &surf);

	// Clean old cache entries
	void pruneCache(int maxEntries = 64);
};

} // End of namespace Scumm

#endif
