/* This file is automatically generated by configure */
/* DO NOT EDIT MANUALLY */

#ifndef CONFIG_H
#define CONFIG_H


#define SCUMM_LITTLE_ENDIAN
#undef SCUMM_BIG_ENDIAN
#undef SCUMM_NEED_ALIGNMENT
#define HAVE_AMD64
#undef WITHOUT_SDL
#undef USE_SDL_NET
#undef USE_ELF_LOADER
#undef DYNAMIC_MODULES
#define DETECTION_STATIC
#define DETECTION_FULL
#define USE_MT32EMU
#undef DISABLE_NUKED_OPL
#define USE_RGB_COLOR
#define USE_HIGHRES
#define USE_SAVEGAME_TIMESTAMP
#define USE_SCALERS
#define USE_HQ_SCALERS
#define USE_EDGE_SCALERS
#define USE_ASPECT
#define USE_OGG
#define USE_VORBIS
#undef USE_TREMOR
#undef ENABLE_OPL2LPT
#undef USE_RETROWAVE
#define USE_FLAC
#define USE_MAD
#undef USE_ALSA
#undef USE_JPEG
#define USE_PNG
#undef USE_FAAD
#define USE_SEQ_MIDI
#undef USE_SNDIO
#define USE_TIMIDITY
#define USE_ZLIB
#undef USE_A52
#undef USE_LIBCURL
#undef USE_BASIC_NET
#undef USE_HTTP
#undef USE_OPENMPT
#undef USE_MIKMOD
#undef USE_DLC
#undef USE_SCUMMVMDLC
#undef USE_FLUIDSYNTH
#undef USE_FLUIDLITE
#undef USE_SONIVOX
#undef USE_READLINE
#undef USE_TEXT_CONSOLE_FOR_DEBUGGER
#undef USE_UNITY
#undef USE_GTK
#undef USE_FREETYPE2
#undef USE_GLES_MODE
#define USE_OPENGL
#define USE_GLAD
#define USE_OPENGL_GAME
#define USE_OPENGL_SHADERS
#define USE_LINUXCD
#undef USE_NASM
#undef USE_PANDOC
#define USE_CURL
#undef USE_FRIBIDI
#undef ENABLE_TEST_CPP_11
#undef USE_DISCORD
#undef ENABLE_VKEYBD
#undef ENABLE_EVENTRECORDER
#define USE_TRANSLATION
#define USE_DETECTLANG
#undef USE_TASKBAR
#define USE_SYSTEM_PRINTING
#undef USE_SYSDIALOGS
#undef USE_TTS
#define USE_BINK
#undef USE_UPDATES
#undef USE_CLOUD
#define BUILTIN_RESOURCES
#define SCUMMVM_SSE2
#define SCUMMVM_AVX2
#undef SCUMMVM_NEON

/* components */
/* #define USE_CDTOONS */
/* #define USE_ENET */
#define USE_FMTOWNS_PC98_AUDIO
/* #define USE_GIF */
/* #define USE_HNM */
/* #define USE_IMGUI */
/* #define USE_INDEO3 */
/* #define USE_INDEO45 */
/* #define USE_JYV1 */
/* #define USE_LUA */
/* #define USE_MFC */
/* #define USE_VPX */
/* #define USE_THEORADEC */
#define USE_MIDI
/* #define USE_MPCDEC */
/* #define USE_MPEG2 */
/* #define USE_QDM2 */
#define USE_SID_AUDIO
/* #define USE_SVQ1 */
/* #define USE_TINYGL */
/* #define USE_TRUEMOTION1 */
/* #define USE_UNIVERSALTRACKER */
/* #define USE_VGMTRANS_AUDIO */
/* #define USE_XAN */
/* end of components */
/* #define TAINTED_BUILD */

#endif /* CONFIG_H */
