# -------- Generated by configure -----------

SAVED_CONFIGFLAGS       := --host=mingw64 --backend=sdl --enable-optimizations --enable-release --disable-all-engines --enable-engine=scumm
SAVED_AR                := 
SAVED_AS                := 
SAVED_ASFLAGS           := 
SAVED_CPPFLAGS          := 
SAVED_CXX               := g++
SAVED_CXXFLAGS          := 
SAVED_CXXFILT           := 
SAVED_DWP               := 
SAVED_LD                := 
SAVED_LDFLAGS           := 
SAVED_NM                := 
SAVED_PKG_CONFIG_LIBDIR := unset
SAVED_RANLIB            := 
SAVED_SDL_CONFIG        := 
SAVED_STRIP             := 
SAVED_WINDRES           := 
SAVED_WINDRESFLAGS      := 

AR := ar cr
AS := as
ASFLAGS := 
CXX := g++
CXXFLAGS :=   -Wshadow -Wno-stringop-overflow -Wno-stringop-truncation -W -Wno-unused-parameter -Wno-empty-body -fno-operator-names -std=gnu++11 -pedantic -Wframe-larger-than=307200 -Wno-address-of-packed-member -O2 -Wuninitialized -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -Werror=return-type
CXXFILT := c++filt
LD := g++
LIBS += -lmingw32 -lwinmm -lgdi32 -LC:/msys64/mingw64/lib -lmingw32  -lSDL2main -lSDL2 -lm -lvorbisfile -lvorbis -lFLAC -logg -lmad -lpng16 -lfaad -lz -L/mingw64/lib -lcurl -lws2_32 -lfluidsynth-3 -ldsound -lksuser -lwinmm -lole32 -lws2_32 -lm C:/msys64/mingw64/lib/libgomp.dll.a C:/msys64/mingw64/lib/libmingwthrd.a -lgthread-2.0 -lintl -lsndfile -lmp3lame -lFLAC -lm -lssp -lvorbisenc -lvorbis -lm -logg -lopus -lm -lmpg123 -lshlwapi -lportaudio -lgmodule-2.0 -lglib-2.0 -lintl -lws2_32 -lole32 -lwinmm -lshlwapi -luuid -latomic -lm -lpcre2-8 -lSDL3  -lm -lkernel32 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8 -lreadline -ltermcap -lfreetype -lfribidi -lole32 -luuid -lwinspool -lole32 -luuid -lsapi -lole32
NM := nm
RANLIB := ranlib
STRIP := strip
DWP := dwp
WINDRES := windres
LDD := ldd
WINDRESFLAGS := 
STAGINGPATH=staging
AMIGAOSPATH=install
MORPHOSPATH=PROGDIR:
STATICLIBPATH=
XCODETOOLSPATH=
SPARKLEPATH=
SDLCONFIG=/mingw64/bin/sdl2-config

ABI := 

BACKEND := sdl
MODULES += backends/platform/sdl
MODULE_DIRS += 
EXEPRE := 
EXEEXT := .exe
NASM := 
NASMFLAGS := 
PANDOC := pandoc
CURL := curl
PANDOCFORMAT := plain
PANDOCEXT := 
MANUALVERSION := latest
ZLIB_LIBS := -lz
ZLIB_CFLAGS := 

prefix = /usr/local
exec_prefix = ${prefix}
bindir = ${exec_prefix}/bin
libdir = ${exec_prefix}/lib
datarootdir = ${prefix}/share
datadir = ${datarootdir}/scummvm
mandir = ${datarootdir}/man
docdir = ${datarootdir}/doc/scummvm


HAVE_GCC = 1
CXX_UPDATE_DEP_FLAG = -MMD -MF "$(*D)/$(DEPDIR)/$(*F).d" -MQ "$@" -MP
WIN32 = 1
SDL_BACKEND = 1
USE_SDL2 = 1
# WITHOUT_SDL = 1
# USE_SDL_NET = 1
# VERBOSE_BUILD = 1
# USE_ELF_LOADER = 1
# DYNAMIC_MODULES = 1
DETECTION_STATIC = 1
DETECTION_FULL = 1
USE_MT32EMU = 1
# DISABLE_NUKED_OPL = 1
USE_RGB_COLOR = 1
USE_HIGHRES = 1
USE_SAVEGAME_TIMESTAMP = 1
USE_SCALERS = 1
USE_HQ_SCALERS = 1
USE_EDGE_SCALERS = 1
USE_ASPECT = 1
USE_OGG = 1
USE_VORBIS = 1
# USE_TREMOR = 1
# ENABLE_OPL2LPT = 1
# USE_RETROWAVE = 1
USE_FLAC = 1
USE_MAD = 1
# USE_ALSA = 1
# USE_JPEG = 1
USE_PNG = 1
USE_FAAD = 1
USE_ZLIB = 1
# USE_A52 = 1
# USE_SPARKLE = 1
USE_LIBCURL = 1
USE_BASIC_NET = 1
USE_HTTP = 1
# USE_OPENMPT = 1
# USE_MIKMOD = 1
# USE_DLC = 1
# USE_SCUMMVMDLC = 1
USE_FLUIDSYNTH = 1
# USE_SONIVOX = 1
USE_FREETYPE2 = 1
USE_OPENGL = 1
USE_GLAD = 1
USE_OPENGL_GAME = 1
USE_OPENGL_SHADERS = 1
# USE_NASM = 1
# USE_PANDOC = 1
USE_CURL = 1
USE_FRIBIDI = 1
# ENABLE_TEST_CPP_11 = 1
# USE_DISCORD = 1
USE_IMGUI_SDLRENDERER2 = 1
# ENABLE_VKEYBD = 1
# ENABLE_EVENTRECORDER = 1
USE_TRANSLATION = 1
USE_TASKBAR = 1
USE_SYSTEM_PRINTING = 1
USE_SYSDIALOGS = 1
USE_TTS = 1
USE_BINK = 1
# USE_UPDATES = 1
USE_CLOUD = 1
BUILTIN_RESOURCES = 1
SCUMMVM_SSE2 = 1
SCUMMVM_AVX2 = 1
# SCUMMVM_NEON = 1
# ENABLE_ACCESS
# ENABLE_ADL
# ENABLE_AGDS
# ENABLE_AGI
# ENABLE_AGOS
# ENABLE_AGOS2
# ENABLE_AGS
# ENABLE_ALCACHOFA
# ENABLE_ALG
# ENABLE_ASYLUM
# ENABLE_AVALANCHE
# ENABLE_AWE
# ENABLE_BAGEL
# ENABLE_BBVS
# ENABLE_BLADERUNNER
# ENABLE_BOLT
# ENABLE_BURIED
# ENABLE_CGE
# ENABLE_CGE2
# ENABLE_CHAMBER
# ENABLE_CHEWY
# ENABLE_CINE
# ENABLE_COLONY
# ENABLE_COMPOSER
# ENABLE_CRAB
# ENABLE_CRUISE
# ENABLE_CRYO
# ENABLE_CRYOMNI3D
# ENABLE_VERSAILLES
# ENABLE_DARKSEED
# ENABLE_DGDS
# ENABLE_DIRECTOR
# ENABLE_DM
# ENABLE_DRACI
# ENABLE_DRAGONS
# ENABLE_DRASCULA
# ENABLE_DREAMWEB
# ENABLE_EFH
# ENABLE_FREESCAPE
# ENABLE_GAMOS
# ENABLE_GLK
# ENABLE_GNAP
# ENABLE_GOB
# ENABLE_GOT
# ENABLE_GRIFFON
# ENABLE_GRIM
# ENABLE_MONKEY4
# ENABLE_GROOVIE
# ENABLE_GROOVIE2
# ENABLE_HADESCH
# ENABLE_HDB
# ENABLE_HOPKINS
# ENABLE_HPL1
# ENABLE_HUGO
# ENABLE_HYPNO
# ENABLE_ICB
# ENABLE_ILLUSIONS
# ENABLE_IMMORTAL
# ENABLE_KINGDOM
# ENABLE_KYRA
# ENABLE_LOL
# ENABLE_EOB
# ENABLE_LAB
# ENABLE_LASTEXPRESS
# ENABLE_LILLIPUT
# ENABLE_LURE
# ENABLE_M4
# ENABLE_MACVENTURE
# ENABLE_MADE
# ENABLE_MADS
# ENABLE_MADSV2
# ENABLE_MEDIASTATION
# ENABLE_MM
# ENABLE_MM1
# ENABLE_XEEN
# ENABLE_MOHAWK
# ENABLE_CSTIME
# ENABLE_RIVEN
# ENABLE_MYST
# ENABLE_MYSTME
# ENABLE_MORTEVIELLE
# ENABLE_MTROPOLIS
# ENABLE_MUTATIONOFJB
# ENABLE_MYST3
# ENABLE_NANCY
# ENABLE_NEVERHOOD
# ENABLE_NGI
# ENABLE_PARALLACTION
# ENABLE_PEGASUS
# ENABLE_PELROCK
# ENABLE_PETKA
# ENABLE_PHOENIXVR
# ENABLE_PINK
# ENABLE_PLAYGROUND3D
# ENABLE_PLUMBERS
# ENABLE_PRINCE
# ENABLE_PRIVATE
# ENABLE_QDENGINE
# ENABLE_QUEEN
# ENABLE_SAGA
# ENABLE_IHNM
# ENABLE_SAGA2
# ENABLE_SCI
# ENABLE_SCI32
ENABLE_SCUMM = STATIC_PLUGIN
ENABLE_SCUMM_7_8 = 1
# ENABLE_HE
# ENABLE_SHERLOCK
# ENABLE_SKY
# ENABLE_SLUDGE
# ENABLE_STARK
# ENABLE_STARTREK
# ENABLE_SUPERNOVA
# ENABLE_SWORD1
# ENABLE_SWORD2
# ENABLE_SWORD25
# ENABLE_TEENAGENT
# ENABLE_TESTBED
# ENABLE_TETRAEDGE
# ENABLE_TINSEL
# ENABLE_TITANIC
# ENABLE_TOLTECS
# ENABLE_TONY
# ENABLE_TOON
# ENABLE_TOT
# ENABLE_TOUCHE
# ENABLE_TRECISION
# ENABLE_TSAGE
# ENABLE_RINGWORLD
# ENABLE_BLUEFORCE
# ENABLE_RINGWORLD2
# ENABLE_TUCKER
# ENABLE_TWINE
# ENABLE_TWP
# ENABLE_ULTIMA
# ENABLE_AKALABETH
# ENABLE_ULTIMA1
# ENABLE_ULTIMA4
# ENABLE_ULTIMA6
# ENABLE_ULTIMA8
# ENABLE_VCRUISE
# ENABLE_VOYEUR
# ENABLE_WAGE
# ENABLE_WATCHMAKER
# ENABLE_WAYNESWORLD
# ENABLE_WINTERMUTE
# ENABLE_WME3D
# ENABLE_FOXTAIL
# ENABLE_HEROCRAFT
# ENABLE_ZVISION

# components
# USE_CDTOONS
# USE_ENET
USE_FMTOWNS_PC98_AUDIO=1
# USE_GIF
# USE_HNM
USE_IMGUI=1
# USE_INDEO3
# USE_INDEO45
# USE_JYV1
# USE_LUA
# USE_MFC
# USE_VPX
# USE_THEORADEC
USE_MIDI=1
# USE_MPCDEC
# USE_MPEG2
# USE_QDM2
USE_SID_AUDIO=1
# USE_SVQ1
# USE_TINYGL
# USE_TRUEMOTION1
# USE_UNIVERSALTRACKER
# USE_VGMTRANS_AUDIO
# USE_XAN
# end of components

INCLUDES += -IC:/msys64/mingw64/include/SDL2     -IC:/msys64/mingw64/include/libpng16    -I/mingw64/include  -IC:/msys64/mingw64/include/fribidi
OBJS += dists/scummvm.o
DEFINES += -DRELEASE_BUILD -DWIN32 -DSDL_BACKEND -DUSE_SDL2 -DPLUGIN_DIRECTORY=\"${exec_prefix}/lib/scummvm\" -DUNICODE -D_UNICODE
LDFLAGS += -static-libgcc -static-libstdc++

PLUGIN_LDFLAGS = 


port_mk = backends/platform/sdl/win32/win32.mk
